version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets.json
      - BUCKET=swfz-cloudrun-storage
      - PROJECT_ID=cloudrunsample-259316
    volumes:
      - ./secrets.json:/secrets.json
